### ISSUE TITLE
Do not log response content if ContentType = application/vnd.ms-excel

### ISSUE THREAD

**Issue by butterdave** [Points/PyLCP#37]
We find the logs really noisy and of no real useful purpose.
As well, we don't want to reveal the contents of the excel file like that

**Comment by greatestape** [comment]
We have this implemented in service container. There might be something useful in there.

**Comment by bradsokol** [comment]
Have a look at #41 and see if that does what you need.

**Comment by butterdave** [comment]
sure does

David Park*  |  *Software Developer

*M:* 416*.*471*.*2649

*Points  |*  More together.

Connect with us: Points.com <http://l.points.com/52r3/> | Twitter
<http://l.points.com/uxlj/> | Blog <http://l.points.com/vu4y/> | LinkedIn
<http://l.points.com/rjs4/>

(TSX: PTS <http://l.points.com/sgf7/>; NASDAQ: PCOM
<http://l.points.com/ko1o/>)

171 John St., 5th Floor, Toronto, ON, M5T 1X3, Canada

Connect with me: LinkedIn <https://www.linkedin.com/in/butterdave>
